# Generated by Django 4.2.9 on 2024-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='update_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
