# Generated by Django 4.2.9 on 2024-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0003_datetimerecord_hourlydata_delete_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlydata',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
