# Generated by Django 4.2.9 on 2024-01-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0004_hourlydata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlydata',
            name='Date',
        ),
    ]
